apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: intelectgame
data:
  MONGODB_URI: "mongodb://mongodb:27017/intelectgame"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  AUTH_SERVICE_URL: "http://auth-service:3001"
  QUIZ_SERVICE_URL: "http://quiz-service:3002"
  GAME_SERVICE_URL: "http://game-service:3003"
  AUTH_SERVICE_PORT: "3001"
  QUIZ_SERVICE_PORT: "3002"
  GAME_SERVICE_PORT: "3003"
  NODE_ENV: "production"

